import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import FullLayout from "@/components/Layout/FullLayout";
import Footer from "@/components/Layout/Footer";
import ReactQueryProviders from "@/components/Layout/ReactQueryProviders";

export const metadata: Metadata = {
  title: "Thinker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ReactQueryProviders>
          <Header />
          <FullLayout>{children}</FullLayout>
          <Footer />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
