import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import FullLayout from "@/components/Layout/FullLayout";

export const metadata: Metadata = {
  title: "Thinker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header />
        <FullLayout>{children}</FullLayout>
      </body>
    </html>
  );
}
