name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master


jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 내가 변수로 저장한 pem key
          host: ${{ secrets.HOST }} # 내가 변수로 저장한 ip
          username: ${{ secrets.USER }} # 내가 변수로 저장한 User
          script: |
            cd Github/thinker/server # 내가 Clone한 폴더 안으로 들어간다.
            git pull # 자동으로 pull해서 주기적 업데이트

  # 깃허브 레파지토리가 프라이빗으로 만들어져 있을때. 
  # git pull https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com/blockenters/streamlit_kmeans.git
